import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { getThemeScript } from '@/stores/useTheme/useTheme';
import { DefaultHeader, Providers } from '@/components/templates';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				suppressHydrationWarning
			>
				<script
					dangerouslySetInnerHTML={{
						__html: getThemeScript(),
					}}
				/>

				<Providers>
					<main>
						<DefaultHeader />
						{children}
					</main>
					<Toaster position="top-center" />
				</Providers>
			</body>
		</html>
	);
}
